// Talismanic advice — unique per hexagram based on trigrams, element, and traditional associations

type LocaleText = { en: string; zh: string; ja: string };

interface ElementTalisman {
  crystals: LocaleText;
  materials: LocaleText;
  wear: LocaleText;
  carry: LocaleText;
  home: LocaleText;
  avoid: LocaleText;
}

const elementTalismans: Record<string, ElementTalisman> = {
  "木": {
    crystals: {
      en: "Green Jade, Malachite, Emerald, Amazonite — these stones resonate with Wood energy, promoting growth, creativity, and new beginnings.",
      zh: "翡翠、孔雀石、祖母绿、天河石——此类宝石与木气共振，助长生机、创意与新生之力。",
      ja: "翡翠、マラカイト、エメラルド、アマゾナイト——これらの石は木のエネルギーと共鳴し、成長、創造性、新しい始まりを促進します。"
    },
    materials: {
      en: "Wear wooden accessories — sandalwood bracelets, bamboo pendants, or natural fiber clothing (cotton, linen). Wood-element people thrive when connected to natural, living materials.",
      zh: "佩戴木质饰品——檀木手串、竹节吊坠，或穿着天然纤维衣物（棉、麻）。木命之人与天然材料相连时最为兴旺。",
      ja: "木製のアクセサリーを身につけましょう——白檀のブレスレット、竹のペンダント、天然繊維の衣服（綿、麻）。木の人は天然の生きた素材とつながるとき最も繁栄します。"
    },
    wear: {
      en: "Wear green, teal, or aqua colors, especially on Mondays and Thursdays. A jade bangle on the left wrist channels Wood energy into your meridian system. Avoid excessive white or metallic accessories.",
      zh: "穿着绿色、青色、碧色衣物，尤以周一、周四为宜。左手佩戴玉镯可引木气入经络。避免过多的白色或金属饰品。",
      ja: "緑、ティール、アクアの色を身につけましょう。特に月曜と木曜が吉です。左手の翡翠のバングルが木のエネルギーを経絡系に導きます。過度な白やメタリックなアクセサリーは避けましょう。"
    },
    carry: {
      en: "Carry a small piece of green jade or a wooden token in your bag. Keep a living plant on your desk — bamboo or a small bonsai. Place a wooden comb on your vanity.",
      zh: "随身携带一小块翡翠或木制令牌。桌上放置活植——富贵竹或小盆景。梳妆台上放一把木梳。",
      ja: "小さな翡翠や木製のトークンをバッグに入れて持ち歩きましょう。机の上に生きた植物を——竹や小さな盆栽がよいでしょう。化粧台に木製の櫛を置いてください。"
    },
    home: {
      en: "Place potted plants in the East and Southeast corners of your home. Hang a wooden wind chime near the entrance. Use wooden furniture and green accents in your decor. Avoid excessive metal decor in living spaces.",
      zh: "家中东方和东南方摆放绿植。入口处悬挂木制风铃。多用木质家具和绿色饰品装饰。避免居住空间过多金属装饰。",
      ja: "家の東と南東の角に鉢植えを置きましょう。玄関近くに木製の風鈴を掛けてください。木製の家具と緑のアクセントを装飾に使いましょう。居住空間に過度な金属装飾は避けてください。"
    },
    avoid: {
      en: "Avoid metal-heavy accessories and environments. Reduce white, gold, and metallic colors in your wardrobe. Limit time in dry, metal-dominated spaces. During autumn (Metal season), strengthen your Wood energy with extra nature time.",
      zh: "避免金属重的饰品和环境。减少衣着中的白色、金色和金属色。减少在干燥、金属感强的空间中停留。秋季金旺之时，多亲近自然以强木气。",
      ja: "金属の多いアクセサリーや環境を避けましょう。ワードローブの白、金、メタリックカラーを減らしてください。乾燥した金属の多い空間での時間を制限しましょう。秋（金の季節）には自然との時間を増やして木のエネルギーを強化してください。"
    }
  },
  "火": {
    crystals: {
      en: "Red Agate, Carnelian, Ruby, Garnet, Sunstone — these fiery stones ignite passion, courage, and personal power. They warm the spirit and fuel creative expression.",
      zh: "红玛瑙、红玉髓、红宝石、石榴石、日长石——此类火性宝石点燃热情、勇气与个人力量。温暖精神，助燃创意表达。",
      ja: "レッドアゲート、カーネリアン、ルビー、ガーネット、サンストーン——これらの火の石は情熱、勇気、個人の力を点火します。精神を温め、創造的表現を促進します。"
    },
    materials: {
      en: "Wear red string bracelets, gold accessories, or leather items. Fire people resonate with warm, bright materials. A small mirror pendant can reflect and amplify your natural radiance.",
      zh: "佩戴红绳手链、金饰或皮具。火命之人与温暖明亮的材质共振。小巧镜面吊坠可反射并放大你天然的光彩。",
      ja: "赤い紐のブレスレット、金のアクセサリー、革製品を身につけましょう。火の人は温かく明るい素材と共鳴します。小さな鏡のペンダントがあなたの自然な輝きを反射し増幅します。"
    },
    wear: {
      en: "Wear red, crimson, purple, or warm orange tones, especially on Tuesdays and Fridays. A red string on the right wrist (traditionally tied by someone who wishes you well) is a classic Fire-element protection.",
      zh: "穿着红色、深红、紫色或暖橙色，尤以周二、周五为宜。右手系红绳（传统上由祝愿你好的人系上）是经典的火元素护身之法。",
      ja: "赤、深紅、紫、暖かいオレンジの色調を身につけましょう。特に火曜と金曜が吉です。右手の赤い紐（伝統的にあなたの幸せを願う人が結ぶ）は古典的な火の元素の守りです。"
    },
    carry: {
      en: "Carry a red agate or carnelian in your pocket. Place a small candle (LED for safety) on your work desk. Keep a red envelope with a coin in your wallet for financial warmth.",
      zh: "随身携带红玛瑙或红玉髓。办公桌上放一小盏灯（安全起见可用LED灯）。钱包中放一个红包内含硬币，招财纳暖。",
      ja: "ポケットにレッドアゲートやカーネリアンを入れて持ち歩きましょう。仕事机に小さなキャンドル（安全のためLEDで）を置いてください。財布にコイン入りの赤い封筒を入れて金運の温かさを保ちましょう。"
    },
    home: {
      en: "Place warm lighting in the South sector of your home. A red or orange accent wall (or artwork) in the living room activates Fire energy. Keep the kitchen — the natural Fire zone — clean and active. Avoid water features like fountains in the South.",
      zh: "家中南方位放置暖色灯光。客厅红色或橙色点缀墙（或挂画）可激活火能。保持厨房——天然的火区——干净且有生气。避免在南方放置水景如喷泉。",
      ja: "家の南セクターに暖かい照明を置きましょう。リビングルームの赤やオレンジのアクセントウォール（またはアート作品）が火のエネルギーを活性化します。キッチン——自然な火のゾーン——を清潔で活気のある状態に保ちましょう。南に噴水などの水の要素を避けてください。"
    },
    avoid: {
      en: "Avoid excessive black, dark blue, and gray in your daily wear — these Water colors dampen your Fire. Limit cold drinks and raw foods which cool your internal fire. During winter, consciously nurture your warmth with spices, warm colors, and social connection.",
      zh: "日常穿着避免过多的黑色、深蓝和灰色——这些水色会压制你的火气。减少冷饮和生冷食物以免冷却内在之火。冬季时，有意识地用香料、暖色和社交来滋养你的温暖。",
      ja: "日常の服装で過度な黒、ダークブルー、グレーを避けましょう——これらの水の色はあなたの火を弱めます。冷たい飲み物や生の食べ物を控え、内なる火を冷やさないようにしましょう。冬はスパイス、暖色、社交で意識的に温かさを育んでください。"
    }
  },
  "土": {
    crystals: {
      en: "Citrine, Yellow Jade, Tiger's Eye, Amber, Smoky Quartz — these grounding stones stabilize, center, and attract abundance. They are the anchors of the crystal world.",
      zh: "黄水晶、黄玉、虎眼石、琥珀、烟晶——此类稳重的宝石安定心神、凝聚中心、吸引丰盛。它们是晶石世界中的锚。",
      ja: "シトリン、イエロージェード、タイガーアイ、琥珀、スモーキークォーツ——これらのグラウンディングストーンは安定させ、中心を定め、豊かさを引き寄せます。クリスタル世界の錨です。"
    },
    materials: {
      en: "Wear ceramic, clay, or stone accessories. Terracotta beads, earthenware pendants, or accessories made from natural stone. Earth people resonate with weight and substance — choose pieces with presence.",
      zh: "佩戴陶瓷、陶土或石制饰品。陶珠、瓦片吊坠或天然石材饰品。土命之人与有分量的物质共振——选择有存在感的饰品。",
      ja: "セラミック、粘土、石のアクセサリーを身につけましょう。テラコッタのビーズ、土器のペンダント、天然石のアクセサリー。土の人は重みと実体と共鳴します——存在感のある作品を選びましょう。"
    },
    wear: {
      en: "Wear brown, yellow, beige, and earth tones, especially on Saturdays. A tiger's eye bracelet on either wrist grounds scattered energy. Avoid excessive green which can unsettle Earth's stability.",
      zh: "穿着棕色、黄色、米色等大地色调，尤以周六为宜。虎眼石手串戴于任意手腕可安定散乱之气。避免过多绿色以免扰乱土的稳定。",
      ja: "茶色、黄色、ベージュ、アースカラーを身につけましょう。特に土曜日が吉です。タイガーアイのブレスレットをどちらかの手首につけると散らばったエネルギーを落ち着けます。過度な緑は土の安定性を乱すので避けましょう。"
    },
    carry: {
      en: "Carry a tiger's eye or citrine stone in your pocket. Place a small pottery bowl on your desk to hold coins or small treasures. Keep a square yellow cloth in your bag — the square represents Earth in Chinese cosmology.",
      zh: "随身携带虎眼石或黄水晶。桌上放一个小陶碗盛放硬币或小物件。包中备一块黄色方巾——方形在中国宇宙观中代表土。",
      ja: "タイガーアイやシトリンをポケットに入れて持ち歩きましょう。机の上に小さな陶器の鉢を置き、コインや小さな宝物を入れます。黄色い四角い布をバッグに入れておきましょう——四角形は中国宇宙論で土を表します。"
    },
    home: {
      en: "Place ceramic or pottery pieces in the center, Southwest, and Northeast of your home. A square rug or table anchors the energy of any room. Use warm earth-tone paints. Keep these areas clutter-free — Earth energy stagnates in mess.",
      zh: "家中中央、西南和东北方摆放陶瓷或陶艺品。方形地毯或桌子可稳住任何房间的气场。使用温暖的土色调涂料。保持这些区域整洁——土气在杂乱中会凝滞。",
      ja: "家の中央、南西、北東に陶器やセラミック作品を置きましょう。四角いラグやテーブルが部屋のエネルギーを固定します。暖かいアースカラーのペイントを使いましょう。これらのエリアを整理整頓してください——土のエネルギーは散らかりの中で停滞します。"
    },
    avoid: {
      en: "Avoid excessive wood and green in your personal space — Wood depletes Earth. Limit time in damp or overly humid environments. Beware of overthinking and worry which are the emotional expressions of imbalanced Earth.",
      zh: "避免个人空间中过多木元素和绿色——木克土。减少在潮湿或过于湿润的环境中停留。警惕过度思虑和担忧，这些是土失衡的情绪表现。",
      ja: "個人空間での過度な木と緑を避けましょう——木は土を消耗させます。湿った環境や過度に多湿な環境での時間を制限してください。考えすぎや心配は土の不調和の感情表現です。"
    }
  },
  "金": {
    crystals: {
      en: "Clear Quartz, Diamond, White Jade, Selenite, Hematite — these crystalline stones embody Metal's clarity, precision, and protective power. They cut through confusion like a sword through mist.",
      zh: "白水晶、钻石、白玉、月光石、赤铁矿——此类金石体现金的明晰、精准与守护之力。如剑劈迷雾般斩断困惑。",
      ja: "クリアクォーツ、ダイヤモンド、ホワイトジェード、セレナイト、ヘマタイト——これらの結晶石は金の明晰さ、正確さ、保護の力を体現します。霧を断つ剣のように混乱を断ち切ります。"
    },
    materials: {
      en: "Wear white metals — silver, white gold, platinum. Metal-element people thrive with clean, polished accessories. A simple silver chain or a pair of white gold studs channels Metal's refined energy. Avoid overly ornate or colorful pieces.",
      zh: "佩戴白色金属——银、白金、铂金。金命之人与干净利落的饰品最为契合。一条简单的银链或一对白金耳钉可引金的精纯之气。避免过于繁复或花哨的饰品。",
      ja: "白い金属——銀、ホワイトゴールド、プラチナを身につけましょう。金の人は清潔で磨かれたアクセサリーと最も調和します。シンプルな銀のチェーンやホワイトゴールドのスタッドピアスが金の洗練されたエネルギーを導きます。過度に装飾的でカラフルなものは避けましょう。"
    },
    wear: {
      en: "Wear white, silver, gray, and champagne tones, especially on Fridays. A silver bracelet on the right wrist enhances decisiveness. White clothing with clean lines supports Metal's need for order and precision.",
      zh: "穿着白色、银色、灰色和香槟色调，尤以周五为宜。右手银镯增强决断力。线条简洁的白色衣物支持金对秩序与精准的需求。",
      ja: "白、シルバー、グレー、シャンパンの色調を身につけましょう。特に金曜日が吉です。右手の銀のブレスレットが決断力を高めます。清潔なラインの白い服が金の秩序と正確さの必要性をサポートします。"
    },
    carry: {
      en: "Carry a clear quartz point or a small metal coin. Place a metal paperweight on your desk. Keep a small mirror compact — Metal's reflective nature aids self-examination. A silver keychain serves as both accessory and talisman.",
      zh: "随身携带白水晶柱或一枚小金属币。桌上放置金属镇纸。随身带一面小镜子——金的反射本质有助自我审视。银质钥匙扣既是饰品也是护符。",
      ja: "クリアクォーツのポイントや小さな金属コインを持ち歩きましょう。机の上に金属の文鎮を置いてください。小さな鏡のコンパクトを持ち歩きましょう——金の反射的な性質が自己検証を助けます。銀のキーホルダーはアクセサリーであり護符でもあります。"
    },
    home: {
      en: "Place metal objects in the West and Northwest sectors. Wind chimes (metal) create protective sound vibrations. Keep spaces organized with clean lines — Metal energy thrives in order. White or gray walls with metal frame decor enhance clarity.",
      zh: "家中西方和西北方放置金属物件。金属风铃产生保护性的声波振动。保持空间整洁有序——金气在秩序中旺盛。白墙灰壁配金属框装饰增强明澈之气。",
      ja: "西と北西のセクターに金属のオブジェを置きましょう。金属の風鈴が保護的な音の波動を生み出します。空間を清潔なラインで整理してください——金のエネルギーは秩序の中で繁栄します。白やグレーの壁に金属フレームの装飾が明晰さを高めます。"
    },
    avoid: {
      en: "Avoid excessive red, pink, and purple in your environment — Fire melts Metal. Reduce exposure to extreme heat. Emotional intensity and drama deplete Metal's refined nature. Seek calm, ordered spaces to recharge.",
      zh: "避免环境中过多的红色、粉色和紫色——火能熔金。减少极端高温的暴露。情绪化的激烈和戏剧化会消耗金的精纯之气。寻找安静有序的空间来充电。",
      ja: "環境での過度な赤、ピンク、紫を避けましょう——火は金を溶かします。極端な熱への露出を減らしてください。感情的な激しさとドラマは金の洗練された性質を消耗させます。再充電のために穏やかで秩序ある空間を求めましょう。"
    }
  },
  "水": {
    crystals: {
      en: "Black Obsidian, Moonstone, Aquamarine, Lapis Lazuli, Pearl — these watery stones deepen intuition, calm the mind, and connect you to ancient wisdom. They are portals to the subconscious.",
      zh: "黑曜石、月光石、海蓝宝、青金石、珍珠——此类水性宝石深化直觉、平静心智、连接古老智慧。它们是通往潜意识的入口。",
      ja: "黒曜石、ムーンストーン、アクアマリン、ラピスラズリ、真珠——これらの水の石は直感を深め、心を静め、古代の知恵とつなげます。潜在意識へのポータルです。"
    },
    materials: {
      en: "Wear pearl, shell, or dark stone accessories. Water people resonate with smooth, cool, flowing materials. A black obsidian pendant protects against negative energy. Avoid overly bright or hot-colored jewelry.",
      zh: "佩戴珍珠、贝壳或深色石饰。水命之人与光滑、清凉、流动性的材质共振。黑曜石吊坠可抵御负面能量。避免过于明亮或暖色调的首饰。",
      ja: "真珠、貝殻、暗い石のアクセサリーを身につけましょう。水の人は滑らかで冷たく流れるような素材と共鳴します。黒曜石のペンダントがネガティブなエネルギーから守ります。過度に明るい色や暖色のジュエリーは避けましょう。"
    },
    wear: {
      en: "Wear black, navy blue, and deep indigo, especially on Wednesdays. A black stone bracelet on the left wrist calms an overactive mind. Flowing, loose-fitting clothing in dark tones supports Water's natural movement.",
      zh: "穿着黑色、藏蓝和深靛蓝，尤以周三为宜。左手佩戴黑石手串可平息过度活跃的思绪。宽松流动的深色衣物支持水的自然流动。",
      ja: "黒、ネイビー、深い藍色を身につけましょう。特に水曜日が吉です。左手の黒い石のブレスレットが過活動な心を落ち着けます。暗い色調のゆったりとした服が水の自然な動きをサポートします。"
    },
    carry: {
      en: "Carry a smooth black stone or a small vial of spring water (symbolically). Keep a small fountain or water feature on your desk. Place a round mirror (representing still water) in your workspace for clarity.",
      zh: "随身携带一枚光滑的黑石或一小瓶泉水（象征性）。桌上放置小型喷泉或水景。工作区域放一面圆镜（代表静水）以助清晰思维。",
      ja: "滑らかな黒い石や小さな湧き水の小瓶（象徴的に）を持ち歩きましょう。机の上に小さな噴水や水の要素を置いてください。作業スペースに丸い鏡（静かな水を表す）を置いて明晰さを助けます。"
    },
    home: {
      en: "Place a small fountain or aquarium in the North sector of your home. Use dark blue or black accent pieces. Keep a bowl of water (changed regularly) near the entrance to absorb and transform negative energy. Curved, flowing shapes in decor support Water energy.",
      zh: "家中北方位放置小型喷泉或鱼缸。使用深蓝或黑色点缀。入门处放一碗水（定期更换）以吸纳转化负面能量。曲线流畅的装饰造型支持水能。",
      ja: "家の北セクターに小さな噴水やアクアリウムを置きましょう。ダークブルーや黒のアクセントピースを使いましょう。玄関近くに水の入った鉢を置き（定期的に交換）、ネガティブなエネルギーを吸収し変換します。曲線的で流れるような形の装飾が水のエネルギーをサポートします。"
    },
    avoid: {
      en: "Avoid excessive brown, yellow, and earth tones — Earth blocks Water. Limit dry, arid environments. Stagnation is Water's enemy — keep your life and spaces flowing and refreshed. Avoid feeling trapped or confined.",
      zh: "避免过多的棕色、黄色和土色调——土克水。减少干燥环境中的停留。停滞是水的敌人——保持生活和空间流动更新。避免感到被困或被限制。",
      ja: "過度な茶色、黄色、アースカラーを避けましょう——土は水をせき止めます。乾燥した環境を制限してください。停滞は水の敵です——人生と空間を流れるように新鮮に保ちましょう。閉じ込められた感覚を避けてください。"
    }
  }
};


export function getBaziTalisman(dayElement: string, locale: string): ElementTalisman & { intro: string } {
  const lang = locale === "zh" ? "zh" : locale === "ja" ? "ja" : "en";
  const talisman = elementTalismans[dayElement] || elementTalismans["土"];

  const intros: Record<string, Record<string, string>> = {
    "木": { en: "As a Wood-element person, your energy thrives on growth, renewal, and connection to nature.", zh: "木命之人，你的气场因生长、更新和与自然的连接而旺盛。", ja: "木のあなたのエネルギーは成長、再生、自然とのつながりによって繁栄します。" },
    "火": { en: "As a Fire-element person, your radiance needs fuel, expression, and warmth to shine brightest.", zh: "火命之人，你的光芒需要燃料、表达和温暖来绽放最亮的光彩。", ja: "火のあなたの輝きは燃料、表現、温かさを必要とします。" },
    "土": { en: "As an Earth-element person, your stability deepens through grounding, ritual, and tangible connection.", zh: "土命之人，你的稳重因扎根、仪式和实在的连接而深厚。", ja: "土のあなたの安定はグラウンディング、儀式、具体的なつながりを通じて深まります。" },
    "金": { en: "As a Metal-element person, your clarity sharpens through refinement, order, and disciplined practice.", zh: "金命之人，你的明澈因精炼、秩序和自律的修行而锐利。", ja: "金のあなたの明晰さは洗練、秩序、規律ある実践を通じて研ぎ澄まされます。" },
    "水": { en: "As a Water-element person, your wisdom deepens through flow, reflection, and connection to the hidden.", zh: "水命之人，你的智慧因流动、反思和与隐藏之物的连接而深邃。", ja: "水のあなたの知恵は流れ、内省、隠れたものとのつながりを通じて深まります。" },
  };

  const intro = intros[dayElement]?.[lang] || intros["土"][lang];

  return {
    intro,
    crystals: talisman.crystals,
    materials: talisman.materials,
    wear: talisman.wear,
    carry: talisman.carry,
    home: talisman.home,
    avoid: talisman.avoid,
  };
}


export function getZhouyiTalisman(hexIdx: number, locale: string): {
  general: string; direction: string; timing: string;
} {
  const lang = locale === "zh" ? "zh" : locale === "ja" ? "ja" : "en";

  const data: Record<number, { gen_en: string; gen_zh: string; gen_ja: string; dir_en: string; dir_zh: string; dir_ja: string; timing_en: string; timing_zh: string; timing_ja: string }> = {
    0: {
      gen_en: "Carry or keep near you a silver coin. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一枚银币。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "銀貨一枚を持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face Northwest (西北) during meditation or important decisions. This is 乾's natural direction — Heaven moves with vigor.",
      dir_zh: "冥想或重要决定时面向西北（西北方）。此为乾之天然方位——Heaven moves with vigor。",
      dir_ja: "瞑想や重要な決断の際は北西（西北）を向く。これは乾の自然な方位——Heaven moves with vigor。",
      timing_en: "Your optimal window: dawn (3:00-5:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：寅时/卯时（3-5时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：寅刻/卯刻（3時-5時）。吉日：金曜/日曜。",
    },
    1: {
      gen_en: "Carry or keep near you a small pottery bowl. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一个小陶碗。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "小さな陶器の鉢を持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Southwest (西南) during meditation or important decisions. This is 坤's natural direction — Earth receives with devotion.",
      dir_zh: "冥想或重要决定时面向西南（西南方）。此为坤之天然方位——Earth receives with devotion。",
      dir_ja: "瞑想や重要な決断の際は南西（西南）を向く。これは坤の自然な方位——Earth receives with devotion。",
      timing_en: "Your optimal window: early afternoon (13:00-15:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：未时/申时（13-15时）。吉日：周六。",
      timing_ja: "最適な時間帯：未刻/申刻（13時-15時）。吉日：土曜。",
    },
    2: {
      gen_en: "Carry or keep near you a navy silk cloth. Flow with events. Journal your thoughts. Take a long bath or walk by water to clear your mind.",
      gen_zh: "随身携带或就近放置一块藏蓝丝巾。随事而流。写下你的思绪。泡个长澡或在水边散步清理思绪。",
      gen_ja: "紺の絹布を持ち歩くか近くに置く。流れに身を任せる。思考を日記に書く。長風呂や水辺の散歩で心を清める。",
      dir_en: "Face North (北) during meditation or important decisions. This is 屯's natural direction — Storm at dawn; initial difficulty.",
      dir_zh: "冥想或重要决定时面向北方（北方）。此为屯之天然方位——Storm at dawn; initial difficulty。",
      dir_ja: "瞑想や重要な決断の際は北（北）を向く。これは屯の自然な方位——Storm at dawn; initial difficulty。",
      timing_en: "Your optimal window: night (21:00-23:00). Best days: Wednesday.",
      timing_zh: "最佳时间窗口：亥时/子时（21-23时）。吉日：周三。",
      timing_ja: "最適な時間帯：亥刻/子刻（21時-23時）。吉日：水曜。",
    },
    3: {
      gen_en: "Carry or keep near you a square clay token. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一枚方形陶令牌。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "四角い粘土のトークンを持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Northeast (东北) during meditation or important decisions. This is 蒙's natural direction — Spring beneath mountain; youthful seeking.",
      dir_zh: "冥想或重要决定时面向东北（东北方）。此为蒙之天然方位——Spring beneath mountain; youthful seeking。",
      dir_ja: "瞑想や重要な決断の際は北東（东北）を向く。これは蒙の自然な方位——Spring beneath mountain; youthful seeking。",
      timing_en: "Your optimal window: early afternoon (13:00-15:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：未时/申时（13-15时）。吉日：周六。",
      timing_ja: "最適な時間帯：未刻/申刻（13時-15時）。吉日：土曜。",
    },
    4: {
      gen_en: "Carry or keep near you a smooth black river stone. Flow with events. Journal your thoughts. Take a long bath or walk by water to clear your mind.",
      gen_zh: "随身携带或就近放置一枚光滑的黑河石。随事而流。写下你的思绪。泡个长澡或在水边散步清理思绪。",
      gen_ja: "滑らかな黒い川石を持ち歩くか近くに置く。流れに身を任せる。思考を日記に書く。長風呂や水辺の散歩で心を清める。",
      dir_en: "Face North (北) during meditation or important decisions. This is 需's natural direction — Clouds rising; waiting with patience.",
      dir_zh: "冥想或重要决定时面向北方（北方）。此为需之天然方位——Clouds rising; waiting with patience。",
      dir_ja: "瞑想や重要な決断の際は北（北）を向く。これは需の自然な方位——Clouds rising; waiting with patience。",
      timing_en: "Your optimal window: night (21:00-23:00). Best days: Wednesday.",
      timing_zh: "最佳时间窗口：亥时/子时（21-23时）。吉日：周三。",
      timing_ja: "最適な時間帯：亥刻/子刻（21時-23時）。吉日：水曜。",
    },
    5: {
      gen_en: "Carry or keep near you a clear quartz crystal. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一颗白水晶柱。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "クリアクォーツの結晶を持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face Northwest (西北) during meditation or important decisions. This is 讼's natural direction — Heaven and water conflict; seek resolution.",
      dir_zh: "冥想或重要决定时面向西北（西北方）。此为讼之天然方位——Heaven and water conflict; seek resolution。",
      dir_ja: "瞑想や重要な決断の際は北西（西北）を向く。これは讼の自然な方位——Heaven and water conflict; seek resolution。",
      timing_en: "Your optimal window: afternoon (15:00-17:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：申时/酉时（15-17时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：申刻/酉刻（15時-17時）。吉日：金曜/日曜。",
    },
    6: {
      gen_en: "Carry or keep near you a yellow silk pouch. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一个黄色丝袋。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "黄色い絹の袋を持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Southwest (西南) during meditation or important decisions. This is 师's natural direction — Army within earth; disciplined action.",
      dir_zh: "冥想或重要决定时面向西南（西南方）。此为师之天然方位——Army within earth; disciplined action。",
      dir_ja: "瞑想や重要な決断の際は南西（西南）を向く。これは师の自然な方位——Army within earth; disciplined action。",
      timing_en: "Your optimal window: deep night (1:00-3:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：丑时/寅时（1-3时）。吉日：周六。",
      timing_ja: "最適な時間帯：丑刻/寅刻（1時-3時）。吉日：土曜。",
    },
    7: {
      gen_en: "Carry or keep near you a conch shell. Flow with events. Journal your thoughts. Take a long bath or walk by water to clear your mind.",
      gen_zh: "随身携带或就近放置一枚海螺壳。随事而流。写下你的思绪。泡个长澡或在水边散步清理思绪。",
      gen_ja: "法螺貝を持ち歩くか近くに置く。流れに身を任せる。思考を日記に書く。長風呂や水辺の散歩で心を清める。",
      dir_en: "Face North (北) during meditation or important decisions. This is 比's natural direction — Water on earth; sincere union.",
      dir_zh: "冥想或重要决定时面向北方（北方）。此为比之天然方位——Water on earth; sincere union。",
      dir_ja: "瞑想や重要な決断の際は北（北）を向く。これは比の自然な方位——Water on earth; sincere union。",
      timing_en: "Your optimal window: morning (7:00-9:00). Best days: Wednesday.",
      timing_zh: "最佳时间窗口：辰时/巳时（7-9时）。吉日：周三。",
      timing_ja: "最適な時間帯：辰刻/巳刻（7時-9時）。吉日：水曜。",
    },
    8: {
      gen_en: "Carry or keep near you a green jade pebble. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一颗绿玉卵石。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "翡翠の小石を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face Southeast (东南) during meditation or important decisions. This is 小畜's natural direction — Gentle wind taming heaven; small gains.",
      dir_zh: "冥想或重要决定时面向东南（东南方）。此为小畜之天然方位——Gentle wind taming heaven; small gains。",
      dir_ja: "瞑想や重要な決断の際は南東（东南）を向く。これは小畜の自然な方位——Gentle wind taming heaven; small gains。",
      timing_en: "Your optimal window: sunrise (5:00-7:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：卯时/辰时（5-7时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：卯刻/辰刻（5時-7時）。吉日：月曜/木曜。",
    },
    9: {
      gen_en: "Carry or keep near you a clear quartz crystal. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一颗白水晶柱。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "クリアクォーツの結晶を持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face Northwest (西北) during meditation or important decisions. This is 履's natural direction — Treading the tiger's tail; careful conduct.",
      dir_zh: "冥想或重要决定时面向西北（西北方）。此为履之天然方位——Treading the tiger's tail; careful conduct。",
      dir_ja: "瞑想や重要な決断の際は北西（西北）を向く。これは履の自然な方位——Treading the tiger's tail; careful conduct。",
      timing_en: "Your optimal window: afternoon (15:00-17:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：申时/酉时（15-17时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：申刻/酉刻（15時-17時）。吉日：金曜/日曜。",
    },
    10: {
      gen_en: "Carry or keep near you a yellow silk pouch. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一个黄色丝袋。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "黄色い絹の袋を持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Southwest (西南) during meditation or important decisions. This is 泰's natural direction — Heaven and earth united; great harmony.",
      dir_zh: "冥想或重要决定时面向西南（西南方）。此为泰之天然方位——Heaven and earth united; great harmony。",
      dir_ja: "瞑想や重要な決断の際は南西（西南）を向く。これは泰の自然な方位——Heaven and earth united; great harmony。",
      timing_en: "Your optimal window: deep night (1:00-3:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：丑时/寅时（1-3时）。吉日：周六。",
      timing_ja: "最適な時間帯：丑刻/寅刻（1時-3時）。吉日：土曜。",
    },
    11: {
      gen_en: "Carry or keep near you a metal mirror. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一面金属镜。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "金属の鏡を持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face Northwest (西北) during meditation or important decisions. This is 否's natural direction — Heaven and earth apart; endurance.",
      dir_zh: "冥想或重要决定时面向西北（西北方）。此为否之天然方位——Heaven and earth apart; endurance。",
      dir_ja: "瞑想や重要な決断の際は北西（西北）を向く。これは否の自然な方位——Heaven and earth apart; endurance。",
      timing_en: "Your optimal window: afternoon (15:00-17:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：申时/酉时（15-17时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：申刻/酉刻（15時-17時）。吉日：金曜/日曜。",
    },
    12: {
      gen_en: "Carry or keep near you a silver coin. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一枚银币。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "銀貨一枚を持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face Northwest (西北) during meditation or important decisions. This is 同人's natural direction — Fire under heaven; fellowship.",
      dir_zh: "冥想或重要决定时面向西北（西北方）。此为同人之天然方位——Fire under heaven; fellowship。",
      dir_ja: "瞑想や重要な決断の際は北西（西北）を向く。これは同人の自然な方位——Fire under heaven; fellowship。",
      timing_en: "Your optimal window: dawn (3:00-5:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：寅时/卯时（3-5时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：寅刻/卯刻（3時-5時）。吉日：金曜/日曜。",
    },
    13: {
      gen_en: "Carry or keep near you a beeswax candle. Express yourself boldly. Wear something bright. Light a candle and state your intention aloud.",
      gen_zh: "随身携带或就近放置一支蜂蜡蜡烛。大胆表达自己。穿戴明亮的颜色。点燃一支蜡烛，大声说出你的意图。",
      gen_ja: "蜜蝋のキャンドルを持ち歩くか近くに置く。大胆に自己表現する。明るい色を身につける。キャンドルを灯し、意図を声に出して宣言する。",
      dir_en: "Face South (南) during meditation or important decisions. This is 大有's natural direction — Sun at zenith; great abundance.",
      dir_zh: "冥想或重要决定时面向南方（南方）。此为大有之天然方位——Sun at zenith; great abundance。",
      dir_ja: "瞑想や重要な決断の際は南（南）を向く。これは大有の自然な方位——Sun at zenith; great abundance。",
      timing_en: "Your optimal window: dusk (17:00-19:00). Best days: Tuesday/Friday.",
      timing_zh: "最佳时间窗口：酉时/戌时（17-19时）。吉日：周二/周五。",
      timing_ja: "最適な時間帯：酉刻/戌刻（17時-19時）。吉日：火曜/金曜。",
    },
    14: {
      gen_en: "Carry or keep near you a yellow silk pouch. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一个黄色丝袋。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "黄色い絹の袋を持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Southwest (西南) during meditation or important decisions. This is 谦's natural direction — Mountain within earth; modesty.",
      dir_zh: "冥想或重要决定时面向西南（西南方）。此为谦之天然方位——Mountain within earth; modesty。",
      dir_ja: "瞑想や重要な決断の際は南西（西南）を向く。これは谦の自然な方位——Mountain within earth; modesty。",
      timing_en: "Your optimal window: deep night (1:00-3:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：丑时/寅时（1-3时）。吉日：周六。",
      timing_ja: "最適な時間帯：丑刻/寅刻（1時-3時）。吉日：土曜。",
    },
    15: {
      gen_en: "Carry or keep near you a wooden comb. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一把木梳。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "木製の櫛を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face East (东) during meditation or important decisions. This is 豫's natural direction — Thunder from earth; joyful enthusiasm.",
      dir_zh: "冥想或重要决定时面向东方（东方）。此为豫之天然方位——Thunder from earth; joyful enthusiasm。",
      dir_ja: "瞑想や重要な決断の際は東（东）を向く。これは豫の自然な方位——Thunder from earth; joyful enthusiasm。",
      timing_en: "Your optimal window: midnight (23:00-1:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：子时/丑时（23-1时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：子刻/丑刻（23時-1時）。吉日：月曜/木曜。",
    },
    16: {
      gen_en: "Carry or keep near you a silver coin. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一枚银币。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "銀貨一枚を持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face West (西) during meditation or important decisions. This is 随's natural direction — Lake over thunder; wise following.",
      dir_zh: "冥想或重要决定时面向西方（西方）。此为随之天然方位——Lake over thunder; wise following。",
      dir_ja: "瞑想や重要な決断の際は西（西）を向く。これは随の自然な方位——Lake over thunder; wise following。",
      timing_en: "Your optimal window: dawn (3:00-5:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：寅时/卯时（3-5时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：寅刻/卯刻（3時-5時）。吉日：金曜/日曜。",
    },
    17: {
      gen_en: "Carry or keep near you a small pottery bowl. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一个小陶碗。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "小さな陶器の鉢を持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Northeast (东北) during meditation or important decisions. This is 蛊's natural direction — Mountain over wind; cleansing decay.",
      dir_zh: "冥想或重要决定时面向东北（东北方）。此为蛊之天然方位——Mountain over wind; cleansing decay。",
      dir_ja: "瞑想や重要な決断の際は北東（东北）を向く。これは蛊の自然な方位——Mountain over wind; cleansing decay。",
      timing_en: "Your optimal window: early afternoon (13:00-15:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：未时/申时（13-15时）。吉日：周六。",
      timing_ja: "最適な時間帯：未刻/申刻（13時-15時）。吉日：土曜。",
    },
    18: {
      gen_en: "Carry or keep near you a yellow silk pouch. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一个黄色丝袋。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "黄色い絹の袋を持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Southwest (西南) during meditation or important decisions. This is 临's natural direction — Earth above lake; approach.",
      dir_zh: "冥想或重要决定时面向西南（西南方）。此为临之天然方位——Earth above lake; approach。",
      dir_ja: "瞑想や重要な決断の際は南西（西南）を向く。これは临の自然な方位——Earth above lake; approach。",
      timing_en: "Your optimal window: deep night (1:00-3:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：丑时/寅时（1-3时）。吉日：周六。",
      timing_ja: "最適な時間帯：丑刻/寅刻（1時-3時）。吉日：土曜。",
    },
    19: {
      gen_en: "Carry or keep near you a wooden comb. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一把木梳。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "木製の櫛を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face Southeast (东南) during meditation or important decisions. This is 观's natural direction — Wind over earth; contemplation.",
      dir_zh: "冥想或重要决定时面向东南（东南方）。此为观之天然方位——Wind over earth; contemplation。",
      dir_ja: "瞑想や重要な決断の際は南東（东南）を向く。これは观の自然な方位——Wind over earth; contemplation。",
      timing_en: "Your optimal window: midnight (23:00-1:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：子时/丑时（23-1时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：子刻/丑刻（23時-1時）。吉日：月曜/木曜。",
    },
    20: {
      gen_en: "Carry or keep near you a red agate stone. Express yourself boldly. Wear something bright. Light a candle and state your intention aloud.",
      gen_zh: "随身携带或就近放置一颗红玛瑙石。大胆表达自己。穿戴明亮的颜色。点燃一支蜡烛，大声说出你的意图。",
      gen_ja: "赤瑪瑙の石を持ち歩くか近くに置く。大胆に自己表現する。明るい色を身につける。キャンドルを灯し、意図を声に出して宣言する。",
      dir_en: "Face South (南) during meditation or important decisions. This is 噬嗑's natural direction — Fire and thunder; biting through.",
      dir_zh: "冥想或重要决定时面向南方（南方）。此为噬嗑之天然方位——Fire and thunder; biting through。",
      dir_ja: "瞑想や重要な決断の際は南（南）を向く。これは噬嗑の自然な方位——Fire and thunder; biting through。",
      timing_en: "Your optimal window: midday (11:00-13:00). Best days: Tuesday/Friday.",
      timing_zh: "最佳时间窗口：午时/未时（11-13时）。吉日：周二/周五。",
      timing_ja: "最適な時間帯：午刻/未刻（11時-13時）。吉日：火曜/金曜。",
    },
    21: {
      gen_en: "Carry or keep near you a small pottery bowl. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一个小陶碗。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "小さな陶器の鉢を持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Northeast (东北) during meditation or important decisions. This is 贲's natural direction — Fire under mountain; grace.",
      dir_zh: "冥想或重要决定时面向东北（东北方）。此为贲之天然方位——Fire under mountain; grace。",
      dir_ja: "瞑想や重要な決断の際は北東（东北）を向く。これは贲の自然な方位——Fire under mountain; grace。",
      timing_en: "Your optimal window: early afternoon (13:00-15:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：未时/申时（13-15时）。吉日：周六。",
      timing_ja: "最適な時間帯：未刻/申刻（13時-15時）。吉日：土曜。",
    },
    22: {
      gen_en: "Carry or keep near you a yellow silk pouch. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一个黄色丝袋。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "黄色い絹の袋を持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Northeast (东北) during meditation or important decisions. This is 剥's natural direction — Mountain over earth; stripping away.",
      dir_zh: "冥想或重要决定时面向东北（东北方）。此为剥之天然方位——Mountain over earth; stripping away。",
      dir_ja: "瞑想や重要な決断の際は北東（东北）を向く。これは剥の自然な方位——Mountain over earth; stripping away。",
      timing_en: "Your optimal window: deep night (1:00-3:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：丑时/寅时（1-3时）。吉日：周六。",
      timing_ja: "最適な時間帯：丑刻/寅刻（1時-3時）。吉日：土曜。",
    },
    23: {
      gen_en: "Carry or keep near you a square clay token. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一枚方形陶令牌。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "四角い粘土のトークンを持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Southwest (西南) during meditation or important decisions. This is 复's natural direction — Thunder within earth; return.",
      dir_zh: "冥想或重要决定时面向西南（西南方）。此为复之天然方位——Thunder within earth; return。",
      dir_ja: "瞑想や重要な決断の際は南西（西南）を向く。これは复の自然な方位——Thunder within earth; return。",
      timing_en: "Your optimal window: early afternoon (13:00-15:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：未时/申时（13-15时）。吉日：周六。",
      timing_ja: "最適な時間帯：未刻/申刻（13時-15時）。吉日：土曜。",
    },
    24: {
      gen_en: "Carry or keep near you a silver coin. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一枚银币。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "銀貨一枚を持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face Northwest (西北) during meditation or important decisions. This is 无妄's natural direction — Thunder under heaven; innocence.",
      dir_zh: "冥想或重要决定时面向西北（西北方）。此为无妄之天然方位——Thunder under heaven; innocence。",
      dir_ja: "瞑想や重要な決断の際は北西（西北）を向く。これは无妄の自然な方位——Thunder under heaven; innocence。",
      timing_en: "Your optimal window: dawn (3:00-5:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：寅时/卯时（3-5时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：寅刻/卯刻（3時-5時）。吉日：金曜/日曜。",
    },
    25: {
      gen_en: "Carry or keep near you a small pottery bowl. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一个小陶碗。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "小さな陶器の鉢を持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Northeast (东北) during meditation or important decisions. This is 大畜's natural direction — Heaven within mountain; great reserves.",
      dir_zh: "冥想或重要决定时面向东北（东北方）。此为大畜之天然方位——Heaven within mountain; great reserves。",
      dir_ja: "瞑想や重要な決断の際は北東（东北）を向く。これは大畜の自然な方位——Heaven within mountain; great reserves。",
      timing_en: "Your optimal window: early afternoon (13:00-15:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：未时/申时（13-15时）。吉日：周六。",
      timing_ja: "最適な時間帯：未刻/申刻（13時-15時）。吉日：土曜。",
    },
    26: {
      gen_en: "Carry or keep near you a yellow silk pouch. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一个黄色丝袋。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "黄色い絹の袋を持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Northeast (东北) during meditation or important decisions. This is 颐's natural direction — Thunder under mountain; nourishment.",
      dir_zh: "冥想或重要决定时面向东北（东北方）。此为颐之天然方位——Thunder under mountain; nourishment。",
      dir_ja: "瞑想や重要な決断の際は北東（东北）を向く。これは颐の自然な方位——Thunder under mountain; nourishment。",
      timing_en: "Your optimal window: deep night (1:00-3:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：丑时/寅时（1-3时）。吉日：周六。",
      timing_ja: "最適な時間帯：丑刻/寅刻（1時-3時）。吉日：土曜。",
    },
    27: {
      gen_en: "Carry or keep near you a metal mirror. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一面金属镜。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "金属の鏡を持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face West (西) during meditation or important decisions. This is 大过's natural direction — Lake over wind; great excess.",
      dir_zh: "冥想或重要决定时面向西方（西方）。此为大过之天然方位——Lake over wind; great excess。",
      dir_ja: "瞑想や重要な決断の際は西（西）を向く。これは大过の自然な方位——Lake over wind; great excess。",
      timing_en: "Your optimal window: afternoon (15:00-17:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：申时/酉时（15-17时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：申刻/酉刻（15時-17時）。吉日：金曜/日曜。",
    },
    28: {
      gen_en: "Carry or keep near you a smooth black river stone. Flow with events. Journal your thoughts. Take a long bath or walk by water to clear your mind.",
      gen_zh: "随身携带或就近放置一枚光滑的黑河石。随事而流。写下你的思绪。泡个长澡或在水边散步清理思绪。",
      gen_ja: "滑らかな黒い川石を持ち歩くか近くに置く。流れに身を任せる。思考を日記に書く。長風呂や水辺の散歩で心を清める。",
      dir_en: "Face North (北) during meditation or important decisions. This is 坎's natural direction — Water doubled; the abyss.",
      dir_zh: "冥想或重要决定时面向北方（北方）。此为坎之天然方位——Water doubled; the abyss。",
      dir_ja: "瞑想や重要な決断の際は北（北）を向く。これは坎の自然な方位——Water doubled; the abyss。",
      timing_en: "Your optimal window: night (21:00-23:00). Best days: Wednesday.",
      timing_zh: "最佳时间窗口：亥时/子时（21-23时）。吉日：周三。",
      timing_ja: "最適な時間帯：亥刻/子刻（21時-23時）。吉日：水曜。",
    },
    29: {
      gen_en: "Carry or keep near you a beeswax candle. Express yourself boldly. Wear something bright. Light a candle and state your intention aloud.",
      gen_zh: "随身携带或就近放置一支蜂蜡蜡烛。大胆表达自己。穿戴明亮的颜色。点燃一支蜡烛，大声说出你的意图。",
      gen_ja: "蜜蝋のキャンドルを持ち歩くか近くに置く。大胆に自己表現する。明るい色を身につける。キャンドルを灯し、意図を声に出して宣言する。",
      dir_en: "Face South (南) during meditation or important decisions. This is 离's natural direction — Fire doubled; radiance.",
      dir_zh: "冥想或重要决定时面向南方（南方）。此为离之天然方位——Fire doubled; radiance。",
      dir_ja: "瞑想や重要な決断の際は南（南）を向く。これは离の自然な方位——Fire doubled; radiance。",
      timing_en: "Your optimal window: dusk (17:00-19:00). Best days: Tuesday/Friday.",
      timing_zh: "最佳时间窗口：酉时/戌时（17-19时）。吉日：周二/周五。",
      timing_ja: "最適な時間帯：酉刻/戌刻（17時-19時）。吉日：火曜/金曜。",
    },
    30: {
      gen_en: "Carry or keep near you a white candle. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一支白蜡烛。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "白いキャンドルを持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face West (西) during meditation or important decisions. This is 咸's natural direction — Lake on mountain; influence.",
      dir_zh: "冥想或重要决定时面向西方（西方）。此为咸之天然方位——Lake on mountain; influence。",
      dir_ja: "瞑想や重要な決断の際は西（西）を向く。これは咸の自然な方位——Lake on mountain; influence。",
      timing_en: "Your optimal window: dawn (3:00-5:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：寅时/卯时（3-5时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：寅刻/卯刻（3時-5時）。吉日：金曜/日曜。",
    },
    31: {
      gen_en: "Carry or keep near you a wooden comb. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一把木梳。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "木製の櫛を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face East (东) during meditation or important decisions. This is 恒's natural direction — Thunder and wind; enduring union.",
      dir_zh: "冥想或重要决定时面向东方（东方）。此为恒之天然方位——Thunder and wind; enduring union。",
      dir_ja: "瞑想や重要な決断の際は東（东）を向く。これは恒の自然な方位——Thunder and wind; enduring union。",
      timing_en: "Your optimal window: midnight (23:00-1:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：子时/丑时（23-1时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：子刻/丑刻（23時-1時）。吉日：月曜/木曜。",
    },
    32: {
      gen_en: "Carry or keep near you a silver coin. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一枚银币。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "銀貨一枚を持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face Northwest (西北) during meditation or important decisions. This is 遁's natural direction — Heaven above mountain; retreat.",
      dir_zh: "冥想或重要决定时面向西北（西北方）。此为遁之天然方位——Heaven above mountain; retreat。",
      dir_ja: "瞑想や重要な決断の際は北西（西北）を向く。これは遁の自然な方位——Heaven above mountain; retreat。",
      timing_en: "Your optimal window: dawn (3:00-5:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：寅时/卯时（3-5时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：寅刻/卯刻（3時-5時）。吉日：金曜/日曜。",
    },
    33: {
      gen_en: "Carry or keep near you a sandalwood bead. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一粒檀木珠。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "白檀の珠を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face East (东) during meditation or important decisions. This is 大壮's natural direction — Thunder in heaven; great power.",
      dir_zh: "冥想或重要决定时面向东方（东方）。此为大壮之天然方位——Thunder in heaven; great power。",
      dir_ja: "瞑想や重要な決断の際は東（东）を向く。これは大壮の自然な方位——Thunder in heaven; great power。",
      timing_en: "Your optimal window: midnight (23:00-1:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：子时/丑时（23-1时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：子刻/丑刻（23時-1時）。吉日：月曜/木曜。",
    },
    34: {
      gen_en: "Carry or keep near you a crimson thread. Express yourself boldly. Wear something bright. Light a candle and state your intention aloud.",
      gen_zh: "随身携带或就近放置一根深红丝线。大胆表达自己。穿戴明亮的颜色。点燃一支蜡烛，大声说出你的意图。",
      gen_ja: "深紅の糸を持ち歩くか近くに置く。大胆に自己表現する。明るい色を身につける。キャンドルを灯し、意図を声に出して宣言する。",
      dir_en: "Face South (南) during meditation or important decisions. This is 晋's natural direction — Fire over earth; steady progress.",
      dir_zh: "冥想或重要决定时面向南方（南方）。此为晋之天然方位——Fire over earth; steady progress。",
      dir_ja: "瞑想や重要な決断の際は南（南）を向く。これは晋の自然な方位——Fire over earth; steady progress。",
      timing_en: "Your optimal window: midday (11:00-13:00). Best days: Tuesday/Friday.",
      timing_zh: "最佳时间窗口：午时/未时（11-13时）。吉日：周二/周五。",
      timing_ja: "最適な時間帯：午刻/未刻（11時-13時）。吉日：火曜/金曜。",
    },
    35: {
      gen_en: "Carry or keep near you a square clay token. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一枚方形陶令牌。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "四角い粘土のトークンを持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Southwest (西南) during meditation or important decisions. This is 明夷's natural direction — Earth over fire; darkened light.",
      dir_zh: "冥想或重要决定时面向西南（西南方）。此为明夷之天然方位——Earth over fire; darkened light。",
      dir_ja: "瞑想や重要な決断の際は南西（西南）を向く。これは明夷の自然な方位——Earth over fire; darkened light。",
      timing_en: "Your optimal window: early afternoon (13:00-15:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：未时/申时（13-15时）。吉日：周六。",
      timing_ja: "最適な時間帯：未刻/申刻（13時-15時）。吉日：土曜。",
    },
    36: {
      gen_en: "Carry or keep near you a green jade pebble. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一颗绿玉卵石。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "翡翠の小石を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face Southeast (东南) during meditation or important decisions. This is 家人's natural direction — Wind from fire; family hearth.",
      dir_zh: "冥想或重要决定时面向东南（东南方）。此为家人之天然方位——Wind from fire; family hearth。",
      dir_ja: "瞑想や重要な決断の際は南東（东南）を向く。これは家人の自然な方位——Wind from fire; family hearth。",
      timing_en: "Your optimal window: sunrise (5:00-7:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：卯时/辰时（5-7时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：卯刻/辰刻（5時-7時）。吉日：月曜/木曜。",
    },
    37: {
      gen_en: "Carry or keep near you a beeswax candle. Express yourself boldly. Wear something bright. Light a candle and state your intention aloud.",
      gen_zh: "随身携带或就近放置一支蜂蜡蜡烛。大胆表达自己。穿戴明亮的颜色。点燃一支蜡烛，大声说出你的意图。",
      gen_ja: "蜜蝋のキャンドルを持ち歩くか近くに置く。大胆に自己表現する。明るい色を身につける。キャンドルを灯し、意図を声に出して宣言する。",
      dir_en: "Face South (南) during meditation or important decisions. This is 睽's natural direction — Fire over lake; opposition.",
      dir_zh: "冥想或重要决定时面向南方（南方）。此为睽之天然方位——Fire over lake; opposition。",
      dir_ja: "瞑想や重要な決断の際は南（南）を向く。これは睽の自然な方位——Fire over lake; opposition。",
      timing_en: "Your optimal window: dusk (17:00-19:00). Best days: Tuesday/Friday.",
      timing_zh: "最佳时间窗口：酉时/戌时（17-19时）。吉日：周二/周五。",
      timing_ja: "最適な時間帯：酉刻/戌刻（17時-19時）。吉日：火曜/金曜。",
    },
    38: {
      gen_en: "Carry or keep near you a navy silk cloth. Flow with events. Journal your thoughts. Take a long bath or walk by water to clear your mind.",
      gen_zh: "随身携带或就近放置一块藏蓝丝巾。随事而流。写下你的思绪。泡个长澡或在水边散步清理思绪。",
      gen_ja: "紺の絹布を持ち歩くか近くに置く。流れに身を任せる。思考を日記に書く。長風呂や水辺の散歩で心を清める。",
      dir_en: "Face North (北) during meditation or important decisions. This is 蹇's natural direction — Water on mountain; obstruction.",
      dir_zh: "冥想或重要决定时面向北方（北方）。此为蹇之天然方位——Water on mountain; obstruction。",
      dir_ja: "瞑想や重要な決断の際は北（北）を向く。これは蹇の自然な方位——Water on mountain; obstruction。",
      timing_en: "Your optimal window: night (21:00-23:00). Best days: Wednesday.",
      timing_zh: "最佳时间窗口：亥时/子时（21-23时）。吉日：周三。",
      timing_ja: "最適な時間帯：亥刻/子刻（21時-23時）。吉日：水曜。",
    },
    39: {
      gen_en: "Carry or keep near you a wooden comb. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一把木梳。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "木製の櫛を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face East (东) during meditation or important decisions. This is 解's natural direction — Thunder over water; deliverance.",
      dir_zh: "冥想或重要决定时面向东方（东方）。此为解之天然方位——Thunder over water; deliverance。",
      dir_ja: "瞑想や重要な決断の際は東（东）を向く。これは解の自然な方位——Thunder over water; deliverance。",
      timing_en: "Your optimal window: midnight (23:00-1:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：子时/丑时（23-1时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：子刻/丑刻（23時-1時）。吉日：月曜/木曜。",
    },
    40: {
      gen_en: "Carry or keep near you a tiger's eye stone. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一颗虎眼石。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "虎目石を持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Northeast (东北) during meditation or important decisions. This is 损's natural direction — Mountain over lake; decrease.",
      dir_zh: "冥想或重要决定时面向东北（东北方）。此为损之天然方位——Mountain over lake; decrease。",
      dir_ja: "瞑想や重要な決断の際は北東（东北）を向く。これは损の自然な方位——Mountain over lake; decrease。",
      timing_en: "Your optimal window: deep night (1:00-3:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：丑时/寅时（1-3时）。吉日：周六。",
      timing_ja: "最適な時間帯：丑刻/寅刻（1時-3時）。吉日：土曜。",
    },
    41: {
      gen_en: "Carry or keep near you a sandalwood bead. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一粒檀木珠。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "白檀の珠を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face Southeast (东南) during meditation or important decisions. This is 益's natural direction — Wind and thunder; increase.",
      dir_zh: "冥想或重要决定时面向东南（东南方）。此为益之天然方位——Wind and thunder; increase。",
      dir_ja: "瞑想や重要な決断の際は南東（东南）を向く。これは益の自然な方位——Wind and thunder; increase。",
      timing_en: "Your optimal window: midnight (23:00-1:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：子时/丑时（23-1时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：子刻/丑刻（23時-1時）。吉日：月曜/木曜。",
    },
    42: {
      gen_en: "Carry or keep near you a white candle. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一支白蜡烛。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "白いキャンドルを持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face West (西) during meditation or important decisions. This is 夬's natural direction — Lake risen to heaven; breakthrough.",
      dir_zh: "冥想或重要决定时面向西方（西方）。此为夬之天然方位——Lake risen to heaven; breakthrough。",
      dir_ja: "瞑想や重要な決断の際は西（西）を向く。これは夬の自然な方位——Lake risen to heaven; breakthrough。",
      timing_en: "Your optimal window: dawn (3:00-5:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：寅时/卯时（3-5时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：寅刻/卯刻（3時-5時）。吉日：金曜/日曜。",
    },
    43: {
      gen_en: "Carry or keep near you a metal mirror. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一面金属镜。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "金属の鏡を持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face Northwest (西北) during meditation or important decisions. This is 姤's natural direction — Heaven above wind; encounter.",
      dir_zh: "冥想或重要决定时面向西北（西北方）。此为姤之天然方位——Heaven above wind; encounter。",
      dir_ja: "瞑想や重要な決断の際は北西（西北）を向く。これは姤の自然な方位——Heaven above wind; encounter。",
      timing_en: "Your optimal window: afternoon (15:00-17:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：申时/酉时（15-17时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：申刻/酉刻（15時-17時）。吉日：金曜/日曜。",
    },
    44: {
      gen_en: "Carry or keep near you a silver coin. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一枚银币。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "銀貨一枚を持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face West (西) during meditation or important decisions. This is 萃's natural direction — Lake over earth; gathering.",
      dir_zh: "冥想或重要决定时面向西方（西方）。此为萃之天然方位——Lake over earth; gathering。",
      dir_ja: "瞑想や重要な決断の際は西（西）を向く。これは萃の自然な方位——Lake over earth; gathering。",
      timing_en: "Your optimal window: dawn (3:00-5:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：寅时/卯时（3-5时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：寅刻/卯刻（3時-5時）。吉日：金曜/日曜。",
    },
    45: {
      gen_en: "Carry or keep near you a small pottery bowl. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一个小陶碗。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "小さな陶器の鉢を持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Southwest (西南) during meditation or important decisions. This is 升's natural direction — Wood from earth; pushing upward.",
      dir_zh: "冥想或重要决定时面向西南（西南方）。此为升之天然方位——Wood from earth; pushing upward。",
      dir_ja: "瞑想や重要な決断の際は南西（西南）を向く。これは升の自然な方位——Wood from earth; pushing upward。",
      timing_en: "Your optimal window: early afternoon (13:00-15:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：未时/申时（13-15时）。吉日：周六。",
      timing_ja: "最適な時間帯：未刻/申刻（13時-15時）。吉日：土曜。",
    },
    46: {
      gen_en: "Carry or keep near you a white candle. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一支白蜡烛。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "白いキャンドルを持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face West (西) during meditation or important decisions. This is 困's natural direction — Lake without water; oppression.",
      dir_zh: "冥想或重要决定时面向西方（西方）。此为困之天然方位——Lake without water; oppression。",
      dir_ja: "瞑想や重要な決断の際は西（西）を向く。これは困の自然な方位——Lake without water; oppression。",
      timing_en: "Your optimal window: dawn (3:00-5:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：寅时/卯时（3-5时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：寅刻/卯刻（3時-5時）。吉日：金曜/日曜。",
    },
    47: {
      gen_en: "Carry or keep near you a conch shell. Flow with events. Journal your thoughts. Take a long bath or walk by water to clear your mind.",
      gen_zh: "随身携带或就近放置一枚海螺壳。随事而流。写下你的思绪。泡个长澡或在水边散步清理思绪。",
      gen_ja: "法螺貝を持ち歩くか近くに置く。流れに身を任せる。思考を日記に書く。長風呂や水辺の散歩で心を清める。",
      dir_en: "Face North (北) during meditation or important decisions. This is 井's natural direction — Water over wood; the well.",
      dir_zh: "冥想或重要决定时面向北方（北方）。此为井之天然方位——Water over wood; the well。",
      dir_ja: "瞑想や重要な決断の際は北（北）を向く。これは井の自然な方位——Water over wood; the well。",
      timing_en: "Your optimal window: morning (7:00-9:00). Best days: Wednesday.",
      timing_zh: "最佳时间窗口：辰时/巳时（7-9时）。吉日：周三。",
      timing_ja: "最適な時間帯：辰刻/巳刻（7時-9時）。吉日：水曜。",
    },
    48: {
      gen_en: "Carry or keep near you a silver coin. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一枚银币。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "銀貨一枚を持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face West (西) during meditation or important decisions. This is 革's natural direction — Fire in lake; revolution.",
      dir_zh: "冥想或重要决定时面向西方（西方）。此为革之天然方位——Fire in lake; revolution。",
      dir_ja: "瞑想や重要な決断の際は西（西）を向く。これは革の自然な方位——Fire in lake; revolution。",
      timing_en: "Your optimal window: dawn (3:00-5:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：寅时/卯时（3-5时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：寅刻/卯刻（3時-5時）。吉日：金曜/日曜。",
    },
    49: {
      gen_en: "Carry or keep near you a beeswax candle. Express yourself boldly. Wear something bright. Light a candle and state your intention aloud.",
      gen_zh: "随身携带或就近放置一支蜂蜡蜡烛。大胆表达自己。穿戴明亮的颜色。点燃一支蜡烛，大声说出你的意图。",
      gen_ja: "蜜蝋のキャンドルを持ち歩くか近くに置く。大胆に自己表現する。明るい色を身につける。キャンドルを灯し、意図を声に出して宣言する。",
      dir_en: "Face South (南) during meditation or important decisions. This is 鼎's natural direction — Fire over wood; the cauldron.",
      dir_zh: "冥想或重要决定时面向南方（南方）。此为鼎之天然方位——Fire over wood; the cauldron。",
      dir_ja: "瞑想や重要な決断の際は南（南）を向く。これは鼎の自然な方位——Fire over wood; the cauldron。",
      timing_en: "Your optimal window: dusk (17:00-19:00). Best days: Tuesday/Friday.",
      timing_zh: "最佳时间窗口：酉时/戌时（17-19时）。吉日：周二/周五。",
      timing_ja: "最適な時間帯：酉刻/戌刻（17時-19時）。吉日：火曜/金曜。",
    },
    50: {
      gen_en: "Carry or keep near you a living bamboo shoot. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一株活竹苗。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "生きた竹の芽を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face East (东) during meditation or important decisions. This is 震's natural direction — Thunder doubled; arousing shock.",
      dir_zh: "冥想或重要决定时面向东方（东方）。此为震之天然方位——Thunder doubled; arousing shock。",
      dir_ja: "瞑想や重要な決断の際は東（东）を向く。これは震の自然な方位——Thunder doubled; arousing shock。",
      timing_en: "Your optimal window: sunrise (5:00-7:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：卯时/辰时（5-7时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：卯刻/辰刻（5時-7時）。吉日：月曜/木曜。",
    },
    51: {
      gen_en: "Carry or keep near you a square clay token. Ground yourself. Walk barefoot on earth. Cook a meal from scratch. Connect with what is solid and real.",
      gen_zh: "随身携带或就近放置一枚方形陶令牌。让自己落地。赤脚走在土地上。亲手做一顿饭。与坚实真实之物连接。",
      gen_ja: "四角い粘土のトークンを持ち歩くか近くに置く。地に足をつける。裸足で大地を歩く。一から料理を作る。固くて現実的なものとつながる。",
      dir_en: "Face Northeast (东北) during meditation or important decisions. This is 艮's natural direction — Mountain doubled; stillness.",
      dir_zh: "冥想或重要决定时面向东北（东北方）。此为艮之天然方位——Mountain doubled; stillness。",
      dir_ja: "瞑想や重要な決断の際は北東（东北）を向く。これは艮の自然な方位——Mountain doubled; stillness。",
      timing_en: "Your optimal window: early afternoon (13:00-15:00). Best days: Saturday.",
      timing_zh: "最佳时间窗口：未时/申时（13-15时）。吉日：周六。",
      timing_ja: "最適な時間帯：未刻/申刻（13時-15時）。吉日：土曜。",
    },
    52: {
      gen_en: "Carry or keep near you a green jade pebble. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一颗绿玉卵石。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "翡翠の小石を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face Southeast (东南) during meditation or important decisions. This is 渐's natural direction — Wood on mountain; gradual progress.",
      dir_zh: "冥想或重要决定时面向东南（东南方）。此为渐之天然方位——Wood on mountain; gradual progress。",
      dir_ja: "瞑想や重要な決断の際は南東（东南）を向く。これは渐の自然な方位——Wood on mountain; gradual progress。",
      timing_en: "Your optimal window: sunrise (5:00-7:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：卯时/辰时（5-7时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：卯刻/辰刻（5時-7時）。吉日：月曜/木曜。",
    },
    53: {
      gen_en: "Carry or keep near you a sandalwood bead. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一粒檀木珠。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "白檀の珠を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face East (东) during meditation or important decisions. This is 归妹's natural direction — Thunder over lake; marrying maiden.",
      dir_zh: "冥想或重要决定时面向东方（东方）。此为归妹之天然方位——Thunder over lake; marrying maiden。",
      dir_ja: "瞑想や重要な決断の際は東（东）を向く。これは归妹の自然な方位——Thunder over lake; marrying maiden。",
      timing_en: "Your optimal window: midnight (23:00-1:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：子时/丑时（23-1时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：子刻/丑刻（23時-1時）。吉日：月曜/木曜。",
    },
    54: {
      gen_en: "Carry or keep near you a living bamboo shoot. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一株活竹苗。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "生きた竹の芽を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face East (东) during meditation or important decisions. This is 丰's natural direction — Thunder and fire; abundance.",
      dir_zh: "冥想或重要决定时面向东方（东方）。此为丰之天然方位——Thunder and fire; abundance。",
      dir_ja: "瞑想や重要な決断の際は東（东）を向く。これは丰の自然な方位——Thunder and fire; abundance。",
      timing_en: "Your optimal window: sunrise (5:00-7:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：卯时/辰时（5-7时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：卯刻/辰刻（5時-7時）。吉日：月曜/木曜。",
    },
    55: {
      gen_en: "Carry or keep near you a small copper coin. Express yourself boldly. Wear something bright. Light a candle and state your intention aloud.",
      gen_zh: "随身携带或就近放置一枚小铜币。大胆表达自己。穿戴明亮的颜色。点燃一支蜡烛，大声说出你的意图。",
      gen_ja: "小さな銅貨を持ち歩くか近くに置く。大胆に自己表現する。明るい色を身につける。キャンドルを灯し、意図を声に出して宣言する。",
      dir_en: "Face South (南) during meditation or important decisions. This is 旅's natural direction — Fire on mountain; the wanderer.",
      dir_zh: "冥想或重要决定时面向南方（南方）。此为旅之天然方位——Fire on mountain; the wanderer。",
      dir_ja: "瞑想や重要な決断の際は南（南）を向く。これは旅の自然な方位——Fire on mountain; the wanderer。",
      timing_en: "Your optimal window: dusk (17:00-19:00). Best days: Tuesday/Friday.",
      timing_zh: "最佳时间窗口：酉时/戌时（17-19时）。吉日：周二/周五。",
      timing_ja: "最適な時間帯：酉刻/戌刻（17時-19時）。吉日：火曜/金曜。",
    },
    56: {
      gen_en: "Carry or keep near you a green jade pebble. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一颗绿玉卵石。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "翡翠の小石を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face Southeast (东南) during meditation or important decisions. This is 巽's natural direction — Wind doubled; gentle penetration.",
      dir_zh: "冥想或重要决定时面向东南（东南方）。此为巽之天然方位——Wind doubled; gentle penetration。",
      dir_ja: "瞑想や重要な決断の際は南東（东南）を向く。これは巽の自然な方位——Wind doubled; gentle penetration。",
      timing_en: "Your optimal window: sunrise (5:00-7:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：卯时/辰时（5-7时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：卯刻/辰刻（5時-7時）。吉日：月曜/木曜。",
    },
    57: {
      gen_en: "Carry or keep near you a clear quartz crystal. Cut through attachment. Declutter your space. Let go of one thing that weighs you down.",
      gen_zh: "随身携带或就近放置一颗白水晶柱。断舍离。清理空间。放下一个拖累你的事物。",
      gen_ja: "クリアクォーツの結晶を持ち歩くか近くに置く。執着を断ち切る。空間を整理する。重荷となるものを一つ手放す。",
      dir_en: "Face West (西) during meditation or important decisions. This is 兑's natural direction — Lake doubled; joy.",
      dir_zh: "冥想或重要决定时面向西方（西方）。此为兑之天然方位——Lake doubled; joy。",
      dir_ja: "瞑想や重要な決断の際は西（西）を向く。これは兑の自然な方位——Lake doubled; joy。",
      timing_en: "Your optimal window: afternoon (15:00-17:00). Best days: Friday/Sunday.",
      timing_zh: "最佳时间窗口：申时/酉时（15-17时）。吉日：周五/周日。",
      timing_ja: "最適な時間帯：申刻/酉刻（15時-17時）。吉日：金曜/日曜。",
    },
    58: {
      gen_en: "Carry or keep near you a living bamboo shoot. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一株活竹苗。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "生きた竹の芽を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face Southeast (东南) during meditation or important decisions. This is 涣's natural direction — Wind over water; dispersion.",
      dir_zh: "冥想或重要决定时面向东南（东南方）。此为涣之天然方位——Wind over water; dispersion。",
      dir_ja: "瞑想や重要な決断の際は南東（东南）を向く。これは涣の自然な方位——Wind over water; dispersion。",
      timing_en: "Your optimal window: sunrise (5:00-7:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：卯时/辰时（5-7时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：卯刻/辰刻（5時-7時）。吉日：月曜/木曜。",
    },
    59: {
      gen_en: "Carry or keep near you a conch shell. Flow with events. Journal your thoughts. Take a long bath or walk by water to clear your mind.",
      gen_zh: "随身携带或就近放置一枚海螺壳。随事而流。写下你的思绪。泡个长澡或在水边散步清理思绪。",
      gen_ja: "法螺貝を持ち歩くか近くに置く。流れに身を任せる。思考を日記に書く。長風呂や水辺の散歩で心を清める。",
      dir_en: "Face North (北) during meditation or important decisions. This is 节's natural direction — Water over lake; limitation.",
      dir_zh: "冥想或重要决定时面向北方（北方）。此为节之天然方位——Water over lake; limitation。",
      dir_ja: "瞑想や重要な決断の際は北（北）を向く。これは节の自然な方位——Water over lake; limitation。",
      timing_en: "Your optimal window: morning (7:00-9:00). Best days: Wednesday.",
      timing_zh: "最佳时间窗口：辰时/巳时（7-9时）。吉日：周三。",
      timing_ja: "最適な時間帯：辰刻/巳刻（7時-9時）。吉日：水曜。",
    },
    60: {
      gen_en: "Carry or keep near you a green jade pebble. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一颗绿玉卵石。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "翡翠の小石を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face Southeast (东南) during meditation or important decisions. This is 中孚's natural direction — Wind over lake; inner truth.",
      dir_zh: "冥想或重要决定时面向东南（东南方）。此为中孚之天然方位——Wind over lake; inner truth。",
      dir_ja: "瞑想や重要な決断の際は南東（东南）を向く。これは中孚の自然な方位——Wind over lake; inner truth。",
      timing_en: "Your optimal window: sunrise (5:00-7:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：卯时/辰时（5-7时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：卯刻/辰刻（5時-7時）。吉日：月曜/木曜。",
    },
    61: {
      gen_en: "Carry or keep near you a sandalwood bead. Plant something new — literally or metaphorically. Start a project. Reach out to someone you've been meaning to contact.",
      gen_zh: "随身携带或就近放置一粒檀木珠。种下新事物——字面上或隐喻上。启动一个项目。联系一个你一直想联系的人。",
      gen_ja: "白檀の珠を持ち歩くか近くに置く。何か新しいものを植える——文字通りに、または比喩的に。プロジェクトを始める。連絡しようと思っていた人に連絡する。",
      dir_en: "Face East (东) during meditation or important decisions. This is 小过's natural direction — Thunder on mountain; small excess.",
      dir_zh: "冥想或重要决定时面向东方（东方）。此为小过之天然方位——Thunder on mountain; small excess。",
      dir_ja: "瞑想や重要な決断の際は東（东）を向く。これは小过の自然な方位——Thunder on mountain; small excess。",
      timing_en: "Your optimal window: midnight (23:00-1:00). Best days: Monday/Thursday.",
      timing_zh: "最佳时间窗口：子时/丑时（23-1时）。吉日：周一/周四。",
      timing_ja: "最適な時間帯：子刻/丑刻（23時-1時）。吉日：月曜/木曜。",
    },
    62: {
      gen_en: "Carry or keep near you a navy silk cloth. Flow with events. Journal your thoughts. Take a long bath or walk by water to clear your mind.",
      gen_zh: "随身携带或就近放置一块藏蓝丝巾。随事而流。写下你的思绪。泡个长澡或在水边散步清理思绪。",
      gen_ja: "紺の絹布を持ち歩くか近くに置く。流れに身を任せる。思考を日記に書く。長風呂や水辺の散歩で心を清める。",
      dir_en: "Face North (北) during meditation or important decisions. This is 既济's natural direction — Water over fire; after completion.",
      dir_zh: "冥想或重要决定时面向北方（北方）。此为既济之天然方位——Water over fire; after completion。",
      dir_ja: "瞑想や重要な決断の際は北（北）を向く。これは既济の自然な方位——Water over fire; after completion。",
      timing_en: "Your optimal window: night (21:00-23:00). Best days: Wednesday.",
      timing_zh: "最佳时间窗口：亥时/子时（21-23时）。吉日：周三。",
      timing_ja: "最適な時間帯：亥刻/子刻（21時-23時）。吉日：水曜。",
    },
    63: {
      gen_en: "Carry or keep near you a small copper coin. Express yourself boldly. Wear something bright. Light a candle and state your intention aloud.",
      gen_zh: "随身携带或就近放置一枚小铜币。大胆表达自己。穿戴明亮的颜色。点燃一支蜡烛，大声说出你的意图。",
      gen_ja: "小さな銅貨を持ち歩くか近くに置く。大胆に自己表現する。明るい色を身につける。キャンドルを灯し、意図を声に出して宣言する。",
      dir_en: "Face South (南) during meditation or important decisions. This is 未济's natural direction — Fire over water; before completion.",
      dir_zh: "冥想或重要决定时面向南方（南方）。此为未济之天然方位——Fire over water; before completion。",
      dir_ja: "瞑想や重要な決断の際は南（南）を向く。これは未济の自然な方位——Fire over water; before completion。",
      timing_en: "Your optimal window: dusk (17:00-19:00). Best days: Tuesday/Friday.",
      timing_zh: "最佳时间窗口：酉时/戌时（17-19时）。吉日：周二/周五。",
      timing_ja: "最適な時間帯：酉刻/戌刻（17時-19時）。吉日：火曜/金曜。",
    },
  };

  const d = data[hexIdx % 64] || data[0];
  if (lang === "zh") return { general: d.gen_zh, direction: d.dir_zh, timing: d.timing_zh };
  if (lang === "ja") return { general: d.gen_ja, direction: d.dir_ja, timing: d.timing_ja };
  return { general: d.gen_en, direction: d.dir_en, timing: d.timing_en };
}
